export { Admin} from './admin.model'
export { Document, DocumentTypes} from './document.model'
export { Course} from './course.model'
export { Class, LearningForms} from './class.model'
export { DocumentClass} from './document-class.model'
export { Student} from './student.model'
export { Teacher} from './teacher.model'
export { StudentClass} from './student-class.model'
export { TeacherClass} from './teacher-class.model'